// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: models/protobuf/listing_gofood.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingGoFood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,proto3" json:"merchant_id,omitempty"`
	SalesChannels []string               `protobuf:"bytes,2,rep,name=sales_channels,proto3" json:"sales_channels,omitempty"`
	Listing       *ListingGoFood_Listing `protobuf:"bytes,3,opt,name=listing,proto3" json:"listing,omitempty"`
}

func (x *ListingGoFood) Reset() {
	*x = ListingGoFood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood) ProtoMessage() {}

func (x *ListingGoFood) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood.ProtoReflect.Descriptor instead.
func (*ListingGoFood) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0}
}

func (x *ListingGoFood) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListingGoFood) GetSalesChannels() []string {
	if x != nil {
		return x.SalesChannels
	}
	return nil
}

func (x *ListingGoFood) GetListing() *ListingGoFood_Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

type ListingGoFood_Listing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId         string                                   `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	Menus             []*ListingGoFood_Listing_Menu            `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
	VariantCategories []*ListingGoFood_Listing_VariantCategory `protobuf:"bytes,3,rep,name=variant_categories,proto3" json:"variant_categories,omitempty"`
}

func (x *ListingGoFood_Listing) Reset() {
	*x = ListingGoFood_Listing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing) ProtoMessage() {}

func (x *ListingGoFood_Listing) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListingGoFood_Listing) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListingGoFood_Listing) GetMenus() []*ListingGoFood_Listing_Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *ListingGoFood_Listing) GetVariantCategories() []*ListingGoFood_Listing_VariantCategory {
	if x != nil {
		return x.VariantCategories
	}
	return nil
}

type ListingGoFood_Listing_Menu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MenuItems []*ListingGoFood_Listing_Menu_MenuItem `protobuf:"bytes,2,rep,name=menu_items,proto3" json:"menu_items,omitempty"`
}

func (x *ListingGoFood_Listing_Menu) Reset() {
	*x = ListingGoFood_Listing_Menu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing_Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing_Menu) ProtoMessage() {}

func (x *ListingGoFood_Listing_Menu) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing_Menu.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing_Menu) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ListingGoFood_Listing_Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGoFood_Listing_Menu) GetMenuItems() []*ListingGoFood_Listing_Menu_MenuItem {
	if x != nil {
		return x.MenuItems
	}
	return nil
}

type ListingGoFood_Listing_VariantCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalId   string                                           `protobuf:"bytes,1,opt,name=external_id,proto3" json:"external_id,omitempty"`
	InternalName string                                           `protobuf:"bytes,2,opt,name=internal_name,proto3" json:"internal_name,omitempty"`
	Name         string                                           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Rules        *ListingGoFood_Listing_VariantCategory_Rule      `protobuf:"bytes,4,opt,name=rules,proto3" json:"rules,omitempty"`
	Variants     []*ListingGoFood_Listing_VariantCategory_Variant `protobuf:"bytes,5,rep,name=variants,proto3" json:"variants,omitempty"`
}

func (x *ListingGoFood_Listing_VariantCategory) Reset() {
	*x = ListingGoFood_Listing_VariantCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing_VariantCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing_VariantCategory) ProtoMessage() {}

func (x *ListingGoFood_Listing_VariantCategory) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing_VariantCategory.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing_VariantCategory) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *ListingGoFood_Listing_VariantCategory) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ListingGoFood_Listing_VariantCategory) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *ListingGoFood_Listing_VariantCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGoFood_Listing_VariantCategory) GetRules() *ListingGoFood_Listing_VariantCategory_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ListingGoFood_Listing_VariantCategory) GetVariants() []*ListingGoFood_Listing_VariantCategory_Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type ListingGoFood_Listing_Menu_MenuItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalId                 string                                               `protobuf:"bytes,1,opt,name=external_id,proto3" json:"external_id,omitempty"`
	Name                       string                                               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                string                                               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InStock                    bool                                                 `protobuf:"varint,4,opt,name=in_stock,proto3" json:"in_stock,omitempty"`
	Price                      float32                                              `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Image                      string                                               `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	OperationalHours           *ListingGoFood_Listing_Menu_MenuItem_OperationalHour `protobuf:"bytes,7,opt,name=operational_hours,proto3" json:"operational_hours,omitempty"`
	VariantCategoryExternalIds []string                                             `protobuf:"bytes,8,rep,name=variant_category_external_ids,proto3" json:"variant_category_external_ids,omitempty"`
}

func (x *ListingGoFood_Listing_Menu_MenuItem) Reset() {
	*x = ListingGoFood_Listing_Menu_MenuItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing_Menu_MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing_Menu_MenuItem) ProtoMessage() {}

func (x *ListingGoFood_Listing_Menu_MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing_Menu_MenuItem.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing_Menu_MenuItem) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *ListingGoFood_Listing_Menu_MenuItem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ListingGoFood_Listing_Menu_MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGoFood_Listing_Menu_MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingGoFood_Listing_Menu_MenuItem) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *ListingGoFood_Listing_Menu_MenuItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingGoFood_Listing_Menu_MenuItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ListingGoFood_Listing_Menu_MenuItem) GetOperationalHours() *ListingGoFood_Listing_Menu_MenuItem_OperationalHour {
	if x != nil {
		return x.OperationalHours
	}
	return nil
}

func (x *ListingGoFood_Listing_Menu_MenuItem) GetVariantCategoryExternalIds() []string {
	if x != nil {
		return x.VariantCategoryExternalIds
	}
	return nil
}

type ListingGoFood_Listing_Menu_MenuItem_OperationalHour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sunday    []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period `protobuf:"bytes,1,rep,name=sunday,proto3" json:"sunday,omitempty"`
	Monday    []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period `protobuf:"bytes,2,rep,name=monday,proto3" json:"monday,omitempty"`
	Tuesday   []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period `protobuf:"bytes,3,rep,name=tuesday,proto3" json:"tuesday,omitempty"`
	Wednesday []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period `protobuf:"bytes,4,rep,name=wednesday,proto3" json:"wednesday,omitempty"`
	Thursday  []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period `protobuf:"bytes,5,rep,name=thursday,proto3" json:"thursday,omitempty"`
	Friday    []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period `protobuf:"bytes,6,rep,name=friday,proto3" json:"friday,omitempty"`
	Saturday  []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period `protobuf:"bytes,7,rep,name=saturday,proto3" json:"saturday,omitempty"`
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) Reset() {
	*x = ListingGoFood_Listing_Menu_MenuItem_OperationalHour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing_Menu_MenuItem_OperationalHour) ProtoMessage() {}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing_Menu_MenuItem_OperationalHour.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing_Menu_MenuItem_OperationalHour) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) GetSunday() []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period {
	if x != nil {
		return x.Sunday
	}
	return nil
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) GetMonday() []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period {
	if x != nil {
		return x.Monday
	}
	return nil
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) GetTuesday() []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period {
	if x != nil {
		return x.Tuesday
	}
	return nil
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) GetWednesday() []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period {
	if x != nil {
		return x.Wednesday
	}
	return nil
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) GetThursday() []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period {
	if x != nil {
		return x.Thursday
	}
	return nil
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) GetFriday() []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period {
	if x != nil {
		return x.Friday
	}
	return nil
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour) GetSaturday() []*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period {
	if x != nil {
		return x.Saturday
	}
	return nil
}

type ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period) Reset() {
	*x = ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period) ProtoMessage() {}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0, 0}
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type ListingGoFood_Listing_VariantCategory_Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selection *ListingGoFood_Listing_VariantCategory_Rule_Selection `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
}

func (x *ListingGoFood_Listing_VariantCategory_Rule) Reset() {
	*x = ListingGoFood_Listing_VariantCategory_Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing_VariantCategory_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing_VariantCategory_Rule) ProtoMessage() {}

func (x *ListingGoFood_Listing_VariantCategory_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing_VariantCategory_Rule.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing_VariantCategory_Rule) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

func (x *ListingGoFood_Listing_VariantCategory_Rule) GetSelection() *ListingGoFood_Listing_VariantCategory_Rule_Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

type ListingGoFood_Listing_VariantCategory_Variant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalId string  `protobuf:"bytes,1,opt,name=external_id,proto3" json:"external_id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price      float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	InStock    bool    `protobuf:"varint,4,opt,name=in_stock,proto3" json:"in_stock,omitempty"`
}

func (x *ListingGoFood_Listing_VariantCategory_Variant) Reset() {
	*x = ListingGoFood_Listing_VariantCategory_Variant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing_VariantCategory_Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing_VariantCategory_Variant) ProtoMessage() {}

func (x *ListingGoFood_Listing_VariantCategory_Variant) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing_VariantCategory_Variant.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing_VariantCategory_Variant) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0, 1, 1}
}

func (x *ListingGoFood_Listing_VariantCategory_Variant) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ListingGoFood_Listing_VariantCategory_Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGoFood_Listing_VariantCategory_Variant) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingGoFood_Listing_VariantCategory_Variant) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

type ListingGoFood_Listing_VariantCategory_Rule_Selection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinQuantity int32 `protobuf:"varint,1,opt,name=min_quantity,proto3" json:"min_quantity,omitempty"`
	MaxQuantity int32 `protobuf:"varint,2,opt,name=max_quantity,proto3" json:"max_quantity,omitempty"`
}

func (x *ListingGoFood_Listing_VariantCategory_Rule_Selection) Reset() {
	*x = ListingGoFood_Listing_VariantCategory_Rule_Selection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_gofood_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGoFood_Listing_VariantCategory_Rule_Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGoFood_Listing_VariantCategory_Rule_Selection) ProtoMessage() {}

func (x *ListingGoFood_Listing_VariantCategory_Rule_Selection) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_gofood_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGoFood_Listing_VariantCategory_Rule_Selection.ProtoReflect.Descriptor instead.
func (*ListingGoFood_Listing_VariantCategory_Rule_Selection) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_gofood_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0}
}

func (x *ListingGoFood_Listing_VariantCategory_Rule_Selection) GetMinQuantity() int32 {
	if x != nil {
		return x.MinQuantity
	}
	return 0
}

func (x *ListingGoFood_Listing_VariantCategory_Rule_Selection) GetMaxQuantity() int32 {
	if x != nil {
		return x.MaxQuantity
	}
	return 0
}

var File_models_protobuf_listing_gofood_proto protoreflect.FileDescriptor

var file_models_protobuf_listing_gofood_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x6f, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x22, 0xd1, 0x10, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f,
	0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x5f, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x61,
	0x6c, 0x65, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x39, 0x0a, 0x07,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0xba, 0x0f, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x12,
	0x5f, 0x0a, 0x12, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f,
	0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x12, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x1a, 0xb1, 0x09, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4d, 0x0a,
	0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xc5, 0x08, 0x0a,
	0x08, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x6b, 0x0a, 0x11, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49,
	0x74, 0x65, 0x6d, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48,
	0x6f, 0x75, 0x72, 0x52, 0x11, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x44, 0x0a, 0x1d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x1d, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x1a, 0xe5, 0x05, 0x0a,
	0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72,
	0x12, 0x5c, 0x0a, 0x06, 0x73, 0x75, 0x6e, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x2e,
	0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x06, 0x73, 0x75, 0x6e, 0x64, 0x61, 0x79, 0x12, 0x5c,
	0x0a, 0x06, 0x6d, 0x6f, 0x6e, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x44,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x2e, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x6f, 0x6e, 0x64, 0x61, 0x79, 0x12, 0x5e, 0x0a, 0x07,
	0x74, 0x75, 0x65, 0x73, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x44, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4d,
	0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x2e, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x52, 0x07, 0x74, 0x75, 0x65, 0x73, 0x64, 0x61, 0x79, 0x12, 0x62, 0x0a, 0x09,
	0x77, 0x65, 0x64, 0x6e, 0x65, 0x73, 0x64, 0x61, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x2e, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x09, 0x77, 0x65, 0x64, 0x6e, 0x65, 0x73, 0x64, 0x61, 0x79,
	0x12, 0x60, 0x0a, 0x08, 0x74, 0x68, 0x75, 0x72, 0x73, 0x64, 0x61, 0x79, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65,
	0x6d, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75,
	0x72, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x08, 0x74, 0x68, 0x75, 0x72, 0x73, 0x64,
	0x61, 0x79, 0x12, 0x5c, 0x0a, 0x06, 0x66, 0x72, 0x69, 0x64, 0x61, 0x79, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65,
	0x6d, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75,
	0x72, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x06, 0x66, 0x72, 0x69, 0x64, 0x61, 0x79,
	0x12, 0x60, 0x0a, 0x08, 0x73, 0x61, 0x74, 0x75, 0x72, 0x64, 0x61, 0x79, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65,
	0x6d, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x75,
	0x72, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x08, 0x73, 0x61, 0x74, 0x75, 0x72, 0x64,
	0x61, 0x79, 0x1a, 0x30, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x1a, 0xbd, 0x04, 0x0a, 0x0f, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4a, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x53, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x08, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x73, 0x1a, 0xb9, 0x01, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x5c,
	0x0a, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x3e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x53, 0x0a, 0x09,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x69, 0x6e,
	0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x6d, 0x69, 0x6e, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a,
	0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x1a, 0x71, 0x0a, 0x07, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x5f, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x79, 0x75, 0x6d, 0x6d, 0x79, 0x2d, 0x63, 0x6f, 0x72, 0x70, 0x2f, 0x79, 0x75,
	0x6d, 0x6d, 0x79, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_models_protobuf_listing_gofood_proto_rawDescOnce sync.Once
	file_models_protobuf_listing_gofood_proto_rawDescData = file_models_protobuf_listing_gofood_proto_rawDesc
)

func file_models_protobuf_listing_gofood_proto_rawDescGZIP() []byte {
	file_models_protobuf_listing_gofood_proto_rawDescOnce.Do(func() {
		file_models_protobuf_listing_gofood_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_protobuf_listing_gofood_proto_rawDescData)
	})
	return file_models_protobuf_listing_gofood_proto_rawDescData
}

var file_models_protobuf_listing_gofood_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_models_protobuf_listing_gofood_proto_goTypes = []interface{}{
	(*ListingGoFood)(nil),                                              // 0: protobuf.ListingGoFood
	(*ListingGoFood_Listing)(nil),                                      // 1: protobuf.ListingGoFood.Listing
	(*ListingGoFood_Listing_Menu)(nil),                                 // 2: protobuf.ListingGoFood.Listing.Menu
	(*ListingGoFood_Listing_VariantCategory)(nil),                      // 3: protobuf.ListingGoFood.Listing.VariantCategory
	(*ListingGoFood_Listing_Menu_MenuItem)(nil),                        // 4: protobuf.ListingGoFood.Listing.Menu.MenuItem
	(*ListingGoFood_Listing_Menu_MenuItem_OperationalHour)(nil),        // 5: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour
	(*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period)(nil), // 6: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.Period
	(*ListingGoFood_Listing_VariantCategory_Rule)(nil),                 // 7: protobuf.ListingGoFood.Listing.VariantCategory.Rule
	(*ListingGoFood_Listing_VariantCategory_Variant)(nil),              // 8: protobuf.ListingGoFood.Listing.VariantCategory.Variant
	(*ListingGoFood_Listing_VariantCategory_Rule_Selection)(nil),       // 9: protobuf.ListingGoFood.Listing.VariantCategory.Rule.Selection
}
var file_models_protobuf_listing_gofood_proto_depIdxs = []int32{
	1,  // 0: protobuf.ListingGoFood.listing:type_name -> protobuf.ListingGoFood.Listing
	2,  // 1: protobuf.ListingGoFood.Listing.menus:type_name -> protobuf.ListingGoFood.Listing.Menu
	3,  // 2: protobuf.ListingGoFood.Listing.variant_categories:type_name -> protobuf.ListingGoFood.Listing.VariantCategory
	4,  // 3: protobuf.ListingGoFood.Listing.Menu.menu_items:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem
	7,  // 4: protobuf.ListingGoFood.Listing.VariantCategory.rules:type_name -> protobuf.ListingGoFood.Listing.VariantCategory.Rule
	8,  // 5: protobuf.ListingGoFood.Listing.VariantCategory.variants:type_name -> protobuf.ListingGoFood.Listing.VariantCategory.Variant
	5,  // 6: protobuf.ListingGoFood.Listing.Menu.MenuItem.operational_hours:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour
	6,  // 7: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.sunday:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.Period
	6,  // 8: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.monday:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.Period
	6,  // 9: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.tuesday:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.Period
	6,  // 10: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.wednesday:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.Period
	6,  // 11: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.thursday:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.Period
	6,  // 12: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.friday:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.Period
	6,  // 13: protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.saturday:type_name -> protobuf.ListingGoFood.Listing.Menu.MenuItem.OperationalHour.Period
	9,  // 14: protobuf.ListingGoFood.Listing.VariantCategory.Rule.selection:type_name -> protobuf.ListingGoFood.Listing.VariantCategory.Rule.Selection
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_models_protobuf_listing_gofood_proto_init() }
func file_models_protobuf_listing_gofood_proto_init() {
	if File_models_protobuf_listing_gofood_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_protobuf_listing_gofood_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing_Menu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing_VariantCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing_Menu_MenuItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing_Menu_MenuItem_OperationalHour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing_Menu_MenuItem_OperationalHour_Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing_VariantCategory_Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing_VariantCategory_Variant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_gofood_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGoFood_Listing_VariantCategory_Rule_Selection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_protobuf_listing_gofood_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_protobuf_listing_gofood_proto_goTypes,
		DependencyIndexes: file_models_protobuf_listing_gofood_proto_depIdxs,
		MessageInfos:      file_models_protobuf_listing_gofood_proto_msgTypes,
	}.Build()
	File_models_protobuf_listing_gofood_proto = out.File
	file_models_protobuf_listing_gofood_proto_rawDesc = nil
	file_models_protobuf_listing_gofood_proto_goTypes = nil
	file_models_protobuf_listing_gofood_proto_depIdxs = nil
}
