// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: models/protobuf/listing_grabfood.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingGrabFood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantId    string                   `protobuf:"bytes,1,opt,name=merchant_id,proto3" json:"merchant_id,omitempty"`
	SalesChannels []string                 `protobuf:"bytes,2,rep,name=sales_channels,proto3" json:"sales_channels,omitempty"`
	Listing       *ListingGrabFood_Listing `protobuf:"bytes,3,opt,name=listing,proto3" json:"listing,omitempty"`
}

func (x *ListingGrabFood) Reset() {
	*x = ListingGrabFood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood) ProtoMessage() {}

func (x *ListingGrabFood) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood.ProtoReflect.Descriptor instead.
func (*ListingGrabFood) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0}
}

func (x *ListingGrabFood) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListingGrabFood) GetSalesChannels() []string {
	if x != nil {
		return x.SalesChannels
	}
	return nil
}

func (x *ListingGrabFood) GetListing() *ListingGrabFood_Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

type ListingGrabFood_Listing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantId        string                                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantID,proto3" json:"merchant_id,omitempty"`
	PartnerMerchantId string                                 `protobuf:"bytes,2,opt,name=partner_merchant_id,json=partnerMerchantID,proto3" json:"partner_merchant_id,omitempty"`
	Currency          *ListingGrabFood_Listing_Currency      `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	SellingTimes      []*ListingGrabFood_Listing_SellingTime `protobuf:"bytes,4,rep,name=selling_times,json=sellingTimes,proto3" json:"selling_times,omitempty"`
	Categories        []*ListingGrabFood_Listing_Category    `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *ListingGrabFood_Listing) Reset() {
	*x = ListingGrabFood_Listing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing) ProtoMessage() {}

func (x *ListingGrabFood_Listing) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListingGrabFood_Listing) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListingGrabFood_Listing) GetPartnerMerchantId() string {
	if x != nil {
		return x.PartnerMerchantId
	}
	return ""
}

func (x *ListingGrabFood_Listing) GetCurrency() *ListingGrabFood_Listing_Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *ListingGrabFood_Listing) GetSellingTimes() []*ListingGrabFood_Listing_SellingTime {
	if x != nil {
		return x.SellingTimes
	}
	return nil
}

func (x *ListingGrabFood_Listing) GetCategories() []*ListingGrabFood_Listing_Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListingGrabFood_Listing_Currency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Exponent int32  `protobuf:"varint,2,opt,name=exponent,proto3" json:"exponent,omitempty"`
	Symbol   string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *ListingGrabFood_Listing_Currency) Reset() {
	*x = ListingGrabFood_Listing_Currency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_Currency) ProtoMessage() {}

func (x *ListingGrabFood_Listing_Currency) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_Currency.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_Currency) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ListingGrabFood_Listing_Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ListingGrabFood_Listing_Currency) GetExponent() int32 {
	if x != nil {
		return x.Exponent
	}
	return 0
}

func (x *ListingGrabFood_Listing_Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type ListingGrabFood_Listing_SellingTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime    string                                           `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime      string                                           `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Id           string                                           `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                                           `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ServiceHours *ListingGrabFood_Listing_SellingTime_ServiceHour `protobuf:"bytes,5,opt,name=service_hours,json=serviceHours,proto3" json:"service_hours,omitempty"`
}

func (x *ListingGrabFood_Listing_SellingTime) Reset() {
	*x = ListingGrabFood_Listing_SellingTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_SellingTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_SellingTime) ProtoMessage() {}

func (x *ListingGrabFood_Listing_SellingTime) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_SellingTime.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_SellingTime) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *ListingGrabFood_Listing_SellingTime) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ListingGrabFood_Listing_SellingTime) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ListingGrabFood_Listing_SellingTime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingGrabFood_Listing_SellingTime) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGrabFood_Listing_SellingTime) GetServiceHours() *ListingGrabFood_Listing_SellingTime_ServiceHour {
	if x != nil {
		return x.ServiceHours
	}
	return nil
}

type ListingGrabFood_Listing_Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SellingTimeId   string                                   `protobuf:"bytes,3,opt,name=selling_time_id,json=sellingTimeID,proto3" json:"selling_time_id,omitempty"`
	AvailableStatus string                                   `protobuf:"bytes,4,opt,name=available_status,json=availableStatus,proto3" json:"available_status,omitempty"`
	Items           []*ListingGrabFood_Listing_Category_Item `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListingGrabFood_Listing_Category) Reset() {
	*x = ListingGrabFood_Listing_Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_Category) ProtoMessage() {}

func (x *ListingGrabFood_Listing_Category) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_Category.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_Category) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *ListingGrabFood_Listing_Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category) GetSellingTimeId() string {
	if x != nil {
		return x.SellingTimeId
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category) GetAvailableStatus() string {
	if x != nil {
		return x.AvailableStatus
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category) GetItems() []*ListingGrabFood_Listing_Category_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListingGrabFood_Listing_SellingTime_ServiceHour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sun *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay `protobuf:"bytes,1,opt,name=sun,proto3" json:"sun,omitempty"`
	Mon *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay `protobuf:"bytes,2,opt,name=mon,proto3" json:"mon,omitempty"`
	Tue *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay `protobuf:"bytes,3,opt,name=tue,proto3" json:"tue,omitempty"`
	Wed *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay `protobuf:"bytes,4,opt,name=wed,proto3" json:"wed,omitempty"`
	Thu *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay `protobuf:"bytes,5,opt,name=thu,proto3" json:"thu,omitempty"`
	Fri *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay `protobuf:"bytes,6,opt,name=fri,proto3" json:"fri,omitempty"`
	Sat *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay `protobuf:"bytes,7,opt,name=sat,proto3" json:"sat,omitempty"`
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) Reset() {
	*x = ListingGrabFood_Listing_SellingTime_ServiceHour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_SellingTime_ServiceHour) ProtoMessage() {}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_SellingTime_ServiceHour.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_SellingTime_ServiceHour) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) GetSun() *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay {
	if x != nil {
		return x.Sun
	}
	return nil
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) GetMon() *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay {
	if x != nil {
		return x.Mon
	}
	return nil
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) GetTue() *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay {
	if x != nil {
		return x.Tue
	}
	return nil
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) GetWed() *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay {
	if x != nil {
		return x.Wed
	}
	return nil
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) GetThu() *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay {
	if x != nil {
		return x.Thu
	}
	return nil
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) GetFri() *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay {
	if x != nil {
		return x.Fri
	}
	return nil
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour) GetSat() *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay {
	if x != nil {
		return x.Sat
	}
	return nil
}

type ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenPeriodType string                                                                      `protobuf:"bytes,1,opt,name=open_period_type,json=openPeriodType,proto3" json:"open_period_type,omitempty"`
	Periods        []*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod `protobuf:"bytes,2,rep,name=periods,proto3" json:"periods,omitempty"`
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay) Reset() {
	*x = ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay) ProtoMessage() {}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0}
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay) GetOpenPeriodType() string {
	if x != nil {
		return x.OpenPeriodType
	}
	return ""
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay) GetPeriods() []*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod {
	if x != nil {
		return x.Periods
	}
	return nil
}

type ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime string `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod) Reset() {
	*x = ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod) ProtoMessage() {}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 1, 0, 0, 0}
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type ListingGrabFood_Listing_Category_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SellingTimeId   string                                                 `protobuf:"bytes,3,opt,name=selling_time_id,json=sellingTimeID,proto3" json:"selling_time_id,omitempty"`
	AvailableStatus string                                                 `protobuf:"bytes,4,opt,name=available_status,json=availableStatus,proto3" json:"available_status,omitempty"`
	Description     string                                                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price           float32                                                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Photos          []string                                               `protobuf:"bytes,7,rep,name=photos,proto3" json:"photos,omitempty"`
	ModifierGroups  []*ListingGrabFood_Listing_Category_Item_ModifierGroup `protobuf:"bytes,8,rep,name=modifier_groups,json=modifierGroups,proto3" json:"modifier_groups,omitempty"`
}

func (x *ListingGrabFood_Listing_Category_Item) Reset() {
	*x = ListingGrabFood_Listing_Category_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_Category_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_Category_Item) ProtoMessage() {}

func (x *ListingGrabFood_Listing_Category_Item) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_Category_Item.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_Category_Item) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 2, 0}
}

func (x *ListingGrabFood_Listing_Category_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item) GetSellingTimeId() string {
	if x != nil {
		return x.SellingTimeId
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item) GetAvailableStatus() string {
	if x != nil {
		return x.AvailableStatus
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingGrabFood_Listing_Category_Item) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *ListingGrabFood_Listing_Category_Item) GetModifierGroups() []*ListingGrabFood_Listing_Category_Item_ModifierGroup {
	if x != nil {
		return x.ModifierGroups
	}
	return nil
}

type ListingGrabFood_Listing_Category_Item_ModifierGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                                                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                                                          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvailableStatus   string                                                          `protobuf:"bytes,3,opt,name=available_status,json=availableStatus,proto3" json:"available_status,omitempty"`
	SelectionRangeMin int32                                                           `protobuf:"varint,4,opt,name=selection_range_min,json=selectionRangeMin,proto3" json:"selection_range_min,omitempty"`
	SelectionRangeMax int32                                                           `protobuf:"varint,5,opt,name=selection_range_max,json=selectionRangeMax,proto3" json:"selection_range_max,omitempty"`
	Modifiers         []*ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier `protobuf:"bytes,6,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) Reset() {
	*x = ListingGrabFood_Listing_Category_Item_ModifierGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_Category_Item_ModifierGroup) ProtoMessage() {}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_Category_Item_ModifierGroup.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_Category_Item_ModifierGroup) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 2, 0, 0}
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) GetAvailableStatus() string {
	if x != nil {
		return x.AvailableStatus
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) GetSelectionRangeMin() int32 {
	if x != nil {
		return x.SelectionRangeMin
	}
	return 0
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) GetSelectionRangeMax() int32 {
	if x != nil {
		return x.SelectionRangeMax
	}
	return 0
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup) GetModifiers() []*ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvailableStatus string  `protobuf:"bytes,3,opt,name=available_status,json=availableStatus,proto3" json:"available_status,omitempty"`
	Price           float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) Reset() {
	*x = ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) ProtoMessage() {}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_listing_grabfood_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier.ProtoReflect.Descriptor instead.
func (*ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) Descriptor() ([]byte, []int) {
	return file_models_protobuf_listing_grabfood_proto_rawDescGZIP(), []int{0, 0, 2, 0, 0, 0}
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) GetAvailableStatus() string {
	if x != nil {
		return x.AvailableStatus
	}
	return ""
}

func (x *ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_models_protobuf_listing_grabfood_proto protoreflect.FileDescriptor

var file_models_protobuf_listing_grabfood_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x61, 0x62, 0x66, 0x6f,
	0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x84, 0x14, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72,
	0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x61, 0x6c, 0x65,
	0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x12, 0x3b, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0xe9, 0x12,
	0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x46, 0x0a, 0x08, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47,
	0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x12, 0x52, 0x0a, 0x0d, 0x73, 0x65, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62,
	0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x0c, 0x73, 0x65, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x4a, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61,
	0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x1a, 0x52, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x1a, 0xb5, 0x08, 0x0a, 0x0b, 0x53, 0x65, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x5e, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72,
	0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53,
	0x65, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48,
	0x6f, 0x75, 0x72, 0x73, 0x1a, 0xe7, 0x06, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x48, 0x6f, 0x75, 0x72, 0x12, 0x56, 0x0a, 0x03, 0x73, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x52, 0x03, 0x73, 0x75, 0x6e, 0x12, 0x56, 0x0a, 0x03,
	0x6d, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62,
	0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x48, 0x6f, 0x75, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x52,
	0x03, 0x6d, 0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x03, 0x74, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x52, 0x03, 0x74, 0x75, 0x65, 0x12, 0x56, 0x0a, 0x03,
	0x77, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62,
	0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x48, 0x6f, 0x75, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x52,
	0x03, 0x77, 0x65, 0x64, 0x12, 0x56, 0x0a, 0x03, 0x74, 0x68, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x52, 0x03, 0x74, 0x68, 0x75, 0x12, 0x56, 0x0a, 0x03,
	0x66, 0x72, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62,
	0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x48, 0x6f, 0x75, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x52,
	0x03, 0x66, 0x72, 0x69, 0x12, 0x56, 0x0a, 0x03, 0x73, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x52, 0x03, 0x73, 0x61, 0x74, 0x1a, 0xef, 0x01, 0x0a,
	0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x6f,
	0x70, 0x65, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x6c, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x52, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f,
	0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x6f, 0x75,
	0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x79, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x07, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x73, 0x1a, 0x49, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x98,
	0x07, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0f, 0x73, 0x65, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x45, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xcd, 0x05, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x65, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x29,
	0x0a, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x66, 0x0a, 0x0f, 0x6d, 0x6f, 0x64,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x0e, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x1a, 0x95, 0x03, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x11, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d,
	0x69, 0x6e, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x11, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d,
	0x61, 0x78, 0x12, 0x64, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x61, 0x62, 0x46, 0x6f, 0x6f, 0x64,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x09, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x1a, 0x6f, 0x0a, 0x08, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x75, 0x6d, 0x6d, 0x79, 0x2d, 0x63, 0x6f,
	0x72, 0x70, 0x2f, 0x79, 0x75, 0x6d, 0x6d, 0x79, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_protobuf_listing_grabfood_proto_rawDescOnce sync.Once
	file_models_protobuf_listing_grabfood_proto_rawDescData = file_models_protobuf_listing_grabfood_proto_rawDesc
)

func file_models_protobuf_listing_grabfood_proto_rawDescGZIP() []byte {
	file_models_protobuf_listing_grabfood_proto_rawDescOnce.Do(func() {
		file_models_protobuf_listing_grabfood_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_protobuf_listing_grabfood_proto_rawDescData)
	})
	return file_models_protobuf_listing_grabfood_proto_rawDescData
}

var file_models_protobuf_listing_grabfood_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_models_protobuf_listing_grabfood_proto_goTypes = []interface{}{
	(*ListingGrabFood)(nil),                                                          // 0: protobuf.ListingGrabFood
	(*ListingGrabFood_Listing)(nil),                                                  // 1: protobuf.ListingGrabFood.Listing
	(*ListingGrabFood_Listing_Currency)(nil),                                         // 2: protobuf.ListingGrabFood.Listing.Currency
	(*ListingGrabFood_Listing_SellingTime)(nil),                                      // 3: protobuf.ListingGrabFood.Listing.SellingTime
	(*ListingGrabFood_Listing_Category)(nil),                                         // 4: protobuf.ListingGrabFood.Listing.Category
	(*ListingGrabFood_Listing_SellingTime_ServiceHour)(nil),                          // 5: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour
	(*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay)(nil),               // 6: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay
	(*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod)(nil), // 7: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay.ServicePeriod
	(*ListingGrabFood_Listing_Category_Item)(nil),                                    // 8: protobuf.ListingGrabFood.Listing.Category.Item
	(*ListingGrabFood_Listing_Category_Item_ModifierGroup)(nil),                      // 9: protobuf.ListingGrabFood.Listing.Category.Item.ModifierGroup
	(*ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier)(nil),             // 10: protobuf.ListingGrabFood.Listing.Category.Item.ModifierGroup.Modifier
}
var file_models_protobuf_listing_grabfood_proto_depIdxs = []int32{
	1,  // 0: protobuf.ListingGrabFood.listing:type_name -> protobuf.ListingGrabFood.Listing
	2,  // 1: protobuf.ListingGrabFood.Listing.currency:type_name -> protobuf.ListingGrabFood.Listing.Currency
	3,  // 2: protobuf.ListingGrabFood.Listing.selling_times:type_name -> protobuf.ListingGrabFood.Listing.SellingTime
	4,  // 3: protobuf.ListingGrabFood.Listing.categories:type_name -> protobuf.ListingGrabFood.Listing.Category
	5,  // 4: protobuf.ListingGrabFood.Listing.SellingTime.service_hours:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour
	8,  // 5: protobuf.ListingGrabFood.Listing.Category.items:type_name -> protobuf.ListingGrabFood.Listing.Category.Item
	6,  // 6: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.sun:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay
	6,  // 7: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.mon:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay
	6,  // 8: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.tue:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay
	6,  // 9: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.wed:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay
	6,  // 10: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.thu:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay
	6,  // 11: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.fri:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay
	6,  // 12: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.sat:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay
	7,  // 13: protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay.periods:type_name -> protobuf.ListingGrabFood.Listing.SellingTime.ServiceHour.ServiceDay.ServicePeriod
	9,  // 14: protobuf.ListingGrabFood.Listing.Category.Item.modifier_groups:type_name -> protobuf.ListingGrabFood.Listing.Category.Item.ModifierGroup
	10, // 15: protobuf.ListingGrabFood.Listing.Category.Item.ModifierGroup.modifiers:type_name -> protobuf.ListingGrabFood.Listing.Category.Item.ModifierGroup.Modifier
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_models_protobuf_listing_grabfood_proto_init() }
func file_models_protobuf_listing_grabfood_proto_init() {
	if File_models_protobuf_listing_grabfood_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_protobuf_listing_grabfood_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_Currency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_SellingTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_SellingTime_ServiceHour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_SellingTime_ServiceHour_ServiceDay_ServicePeriod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_Category_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_Category_Item_ModifierGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_listing_grabfood_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingGrabFood_Listing_Category_Item_ModifierGroup_Modifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_protobuf_listing_grabfood_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_protobuf_listing_grabfood_proto_goTypes,
		DependencyIndexes: file_models_protobuf_listing_grabfood_proto_depIdxs,
		MessageInfos:      file_models_protobuf_listing_grabfood_proto_msgTypes,
	}.Build()
	File_models_protobuf_listing_grabfood_proto = out.File
	file_models_protobuf_listing_grabfood_proto_rawDesc = nil
	file_models_protobuf_listing_grabfood_proto_goTypes = nil
	file_models_protobuf_listing_grabfood_proto_depIdxs = nil
}
