// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.1
// source: models/protobuf/promotion_yfc.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YfcPromotion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Promotions []*YfcPromotion_Promotions `protobuf:"bytes,1,rep,name=promotions,proto3" json:"promotions,omitempty"`
}

func (x *YfcPromotion) Reset() {
	*x = YfcPromotion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_promotion_yfc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YfcPromotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YfcPromotion) ProtoMessage() {}

func (x *YfcPromotion) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_promotion_yfc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YfcPromotion.ProtoReflect.Descriptor instead.
func (*YfcPromotion) Descriptor() ([]byte, []int) {
	return file_models_protobuf_promotion_yfc_proto_rawDescGZIP(), []int{0}
}

func (x *YfcPromotion) GetPromotions() []*YfcPromotion_Promotions {
	if x != nil {
		return x.Promotions
	}
	return nil
}

type YfcPromotion_Promotions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku        string  `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price      float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	StartDate  int64   `protobuf:"varint,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate    int64   `protobuf:"varint,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	MerchantID string  `protobuf:"bytes,6,opt,name=merchantID,json=merchantId,proto3" json:"merchantID,omitempty"`
}

func (x *YfcPromotion_Promotions) Reset() {
	*x = YfcPromotion_Promotions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_promotion_yfc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YfcPromotion_Promotions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YfcPromotion_Promotions) ProtoMessage() {}

func (x *YfcPromotion_Promotions) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_promotion_yfc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YfcPromotion_Promotions.ProtoReflect.Descriptor instead.
func (*YfcPromotion_Promotions) Descriptor() ([]byte, []int) {
	return file_models_protobuf_promotion_yfc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *YfcPromotion_Promotions) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *YfcPromotion_Promotions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YfcPromotion_Promotions) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *YfcPromotion_Promotions) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *YfcPromotion_Promotions) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *YfcPromotion_Promotions) GetMerchantID() string {
	if x != nil {
		return x.MerchantID
	}
	return ""
}

var File_models_protobuf_promotion_yfc_proto protoreflect.FileDescriptor

var file_models_protobuf_promotion_yfc_proto_rawDesc = []byte{
	0x0a, 0x23, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x66, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22,
	0xf4, 0x01, 0x0a, 0x0c, 0x59, 0x66, 0x63, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x41, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x59, 0x66, 0x63, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x1a, 0xa0, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x6b, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x75, 0x6d, 0x6d, 0x79, 0x2d, 0x63, 0x6f, 0x72, 0x70, 0x2f,
	0x79, 0x75, 0x6d, 0x6d, 0x79, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_protobuf_promotion_yfc_proto_rawDescOnce sync.Once
	file_models_protobuf_promotion_yfc_proto_rawDescData = file_models_protobuf_promotion_yfc_proto_rawDesc
)

func file_models_protobuf_promotion_yfc_proto_rawDescGZIP() []byte {
	file_models_protobuf_promotion_yfc_proto_rawDescOnce.Do(func() {
		file_models_protobuf_promotion_yfc_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_protobuf_promotion_yfc_proto_rawDescData)
	})
	return file_models_protobuf_promotion_yfc_proto_rawDescData
}

var file_models_protobuf_promotion_yfc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_protobuf_promotion_yfc_proto_goTypes = []interface{}{
	(*YfcPromotion)(nil),            // 0: protobuf.YfcPromotion
	(*YfcPromotion_Promotions)(nil), // 1: protobuf.YfcPromotion.Promotions
}
var file_models_protobuf_promotion_yfc_proto_depIdxs = []int32{
	1, // 0: protobuf.YfcPromotion.promotions:type_name -> protobuf.YfcPromotion.Promotions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_protobuf_promotion_yfc_proto_init() }
func file_models_protobuf_promotion_yfc_proto_init() {
	if File_models_protobuf_promotion_yfc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_protobuf_promotion_yfc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YfcPromotion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protobuf_promotion_yfc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YfcPromotion_Promotions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_protobuf_promotion_yfc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_protobuf_promotion_yfc_proto_goTypes,
		DependencyIndexes: file_models_protobuf_promotion_yfc_proto_depIdxs,
		MessageInfos:      file_models_protobuf_promotion_yfc_proto_msgTypes,
	}.Build()
	File_models_protobuf_promotion_yfc_proto = out.File
	file_models_protobuf_promotion_yfc_proto_rawDesc = nil
	file_models_protobuf_promotion_yfc_proto_goTypes = nil
	file_models_protobuf_promotion_yfc_proto_depIdxs = nil
}
