// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.1
// source: models/protobuf/sync_oms_update_status.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncOmsUpdateStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderName     string `protobuf:"bytes,1,opt,name=providerName,proto3" json:"providerName,omitempty"`
	MerchantId       string `protobuf:"bytes,2,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	OrderId          string `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
	SyncStatus       string `protobuf:"bytes,4,opt,name=syncStatus,proto3" json:"syncStatus,omitempty"`
	SyncMessage      string `protobuf:"bytes,5,opt,name=syncMessage,proto3" json:"syncMessage,omitempty"`
	EventName        string `protobuf:"bytes,6,opt,name=eventName,proto3" json:"eventName,omitempty"`
	OrderStatus      string `protobuf:"bytes,7,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	ShortOrderNumber string `protobuf:"bytes,8,opt,name=shortOrderNumber,proto3" json:"shortOrderNumber,omitempty"`
}

func (x *SyncOmsUpdateStatus) Reset() {
	*x = SyncOmsUpdateStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protobuf_sync_oms_update_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncOmsUpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOmsUpdateStatus) ProtoMessage() {}

func (x *SyncOmsUpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_models_protobuf_sync_oms_update_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOmsUpdateStatus.ProtoReflect.Descriptor instead.
func (*SyncOmsUpdateStatus) Descriptor() ([]byte, []int) {
	return file_models_protobuf_sync_oms_update_status_proto_rawDescGZIP(), []int{0}
}

func (x *SyncOmsUpdateStatus) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SyncOmsUpdateStatus) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *SyncOmsUpdateStatus) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SyncOmsUpdateStatus) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *SyncOmsUpdateStatus) GetSyncMessage() string {
	if x != nil {
		return x.SyncMessage
	}
	return ""
}

func (x *SyncOmsUpdateStatus) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *SyncOmsUpdateStatus) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *SyncOmsUpdateStatus) GetShortOrderNumber() string {
	if x != nil {
		return x.ShortOrderNumber
	}
	return ""
}

var File_models_protobuf_sync_oms_update_status_proto protoreflect.FileDescriptor

var file_models_protobuf_sync_oms_update_status_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x6f, 0x6d, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0xa1, 0x02, 0x0a, 0x13, 0x53, 0x79, 0x6e,
	0x63, 0x4f, 0x6d, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2a, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x75, 0x6d, 0x6d, 0x79,
	0x2d, 0x63, 0x6f, 0x72, 0x70, 0x2f, 0x79, 0x75, 0x6d, 0x6d, 0x79, 0x6f, 0x73, 0x2d, 0x73, 0x70,
	0x65, 0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_protobuf_sync_oms_update_status_proto_rawDescOnce sync.Once
	file_models_protobuf_sync_oms_update_status_proto_rawDescData = file_models_protobuf_sync_oms_update_status_proto_rawDesc
)

func file_models_protobuf_sync_oms_update_status_proto_rawDescGZIP() []byte {
	file_models_protobuf_sync_oms_update_status_proto_rawDescOnce.Do(func() {
		file_models_protobuf_sync_oms_update_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_protobuf_sync_oms_update_status_proto_rawDescData)
	})
	return file_models_protobuf_sync_oms_update_status_proto_rawDescData
}

var file_models_protobuf_sync_oms_update_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_protobuf_sync_oms_update_status_proto_goTypes = []interface{}{
	(*SyncOmsUpdateStatus)(nil), // 0: protobuf.SyncOmsUpdateStatus
}
var file_models_protobuf_sync_oms_update_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_protobuf_sync_oms_update_status_proto_init() }
func file_models_protobuf_sync_oms_update_status_proto_init() {
	if File_models_protobuf_sync_oms_update_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_protobuf_sync_oms_update_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncOmsUpdateStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_protobuf_sync_oms_update_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_protobuf_sync_oms_update_status_proto_goTypes,
		DependencyIndexes: file_models_protobuf_sync_oms_update_status_proto_depIdxs,
		MessageInfos:      file_models_protobuf_sync_oms_update_status_proto_msgTypes,
	}.Build()
	File_models_protobuf_sync_oms_update_status_proto = out.File
	file_models_protobuf_sync_oms_update_status_proto_rawDesc = nil
	file_models_protobuf_sync_oms_update_status_proto_goTypes = nil
	file_models_protobuf_sync_oms_update_status_proto_depIdxs = nil
}
